-- [5] Sequence : 순차적인 번호를 자동으로 생성하는 객체로 테이블과 독립적으로 생성 및 저장 가능
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH   1 -- 1부터 시작(기본값)
    INCREMENT BY 1 -- 1씩 증가(기본값)
    MAXVALUE     9999 -- 최대값
    MINVALUE     1    -- 최소값
    NOCYCLE -- CYCLE : 순차번호 9999->1
    NOCACHE;
SELECT FRIEND_SEQ.NEXTVAL FROM DUAL; -- 다음 순차번호 값
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; -- 현재 시퀸스 값

DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NO NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    TEL VARCHAR2(20) UNIQUE,
    ADDRESS VARCHAR2(250),
    LAST_MODIFY DATE DEFAULT SYSDATE
);
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 99999
    NOCACHE NOCYCLE;
SELECT * FROM FRIEND;
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', '010-9999-9999','서울');
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '유길동', NULL,'서울');
SELECT * FROM FRIEND;
DELETE FROM FRIEND WHERE TEL IS NULL;
SELECT * FROM FRIEND;

-- ※ 연습문제
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;
DROP SEQUENCE MEMBER_SQ;
CREATE TABLE MEMBER_LEVEL();
CREATE TABLE MEMBER();
CREATE SEQUENCE MEMBER_SQ ~
-- INSERT INTO MEMBER_LEVEL ~
-- INSERT INTO MEMBER_LEVEL ~

-- 기존 테이블 및 시퀀스 삭제
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;
DROP SEQUENCE MEMBER_SQ;

-- 회원 등급 테이블 생성
CREATE TABLE MEMBER_LEVEL (
    LEVELNO    NUMBER(1) PRIMARY KEY,
    LEVELNAME  VARCHAR2(20)
);

-- 회원 테이블 생성
CREATE TABLE MEMBER (
    MNO      NUMBER PRIMARY KEY,              -- 회원번호
    MNAME    VARCHAR2(20),                    -- 이름
    MPW      VARCHAR2(10),                    -- 비밀번호
    MMAIL    VARCHAR2(50),                    -- 이메일
    MPOINT   NUMBER(5),                       -- 포인트
    MRDATE   DATE DEFAULT SYSDATE,            -- 가입일
    LEVELNO  NUMBER(1),                       -- 회원등급
    FOREIGN KEY (LEVELNO) REFERENCES MEMBER_LEVEL(LEVELNO)
);

-- 시퀀스 생성
CREATE SEQUENCE MEMBER_SQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

-- MEMBER_LEVEL 데이터 삽입
INSERT INTO MEMBER_LEVEL VALUES (-1, 'black');
INSERT INTO MEMBER_LEVEL VALUES (0, '일반 고객');
INSERT INTO MEMBER_LEVEL VALUES (1, '실버 고객');
INSERT INTO MEMBER_LEVEL VALUES (2, '골드 고객');

-- MEMBER 데이터 삽입
INSERT INTO MEMBER VALUES (MEMBER_SQ.NEXTVAL, '홍길동', 'aa', 'hong@hong.com', 0, TO_DATE('2022-03-10', 'YYYY-MM-DD'), 0);
INSERT INTO MEMBER VALUES (MEMBER_SQ.NEXTVAL, '신길동', 'bb', 'sin@sin.com', 1000, TO_DATE('2022-04-01', 'YYYY-MM-DD'), 1);

-- JOIN 결과 출력 (테스트 출력 내용과 일치)
SELECT 
    M.MNO,
    M.MNAME,
    TO_CHAR(M.MRDATE, 'YYYY-MM-DD') AS 가입일자,
    M.MMAIL,
    M.MPOINT AS POINT,
    L.LEVELNAME AS 등급
FROM MEMBER M
JOIN MEMBER_LEVEL L ON M.LEVELNO = L.LEVELNO;
